name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          css: false
          
      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose --no-progress --accept 200,403
            --exclude '^https://fonts\.googleapis\.com/$'
            --exclude '^https://fonts\.gstatic\.com/$'
            './**/*.html'
          fail: true
